modLoader="javafml"
loaderVersion="[40,)"
license="MIT License"
issueTrackerURL="https://github.com/brdle/More-Horse-Armor/issues"


[[mods]]
modId="morehorsearmor"
version="${file.jarVersion}"
displayName="More Horse Armor"
displayURL="https://www.curseforge.com/minecraft/mc-mods/more-horse-armor"
updateJSONURL="https://onvoid.net/morehorsearmor/update.json"
logoFile="morehorsearmor.png"
logoBlur=false
credits="brdle, LieOnLion (textures)"
authors="brdle, LieOnLion"
description="Adds Netherite & Enderite Horse Armors."
itemIcon="morehorsearmor:netherite_horse_armor"
configBackground="minecraft:textures/block/netherite_block.png"

[[dependencies.morehorsearmor]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"